//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo4jDotNetDemo
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class poa
    {
        public int idPOA { get; set; }
        public int Blankid { get; set; }
        public System.DateTime SertDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public bool Irrevocable { get; set; }
        public int NumInReg { get; set; }
        public int Person_idPerson { get; set; }
        public int Subject_idSubject { get; set; }
        public Nullable<int> idWitness { get; set; }
        public int IdRegistrator { get; set; }
        [JsonIgnore]
        public Nullable<int> Suspention_idSuspention { get; set; }

        [JsonIgnore]
        public virtual notary notary { get; set; }
        [JsonIgnore]
        public virtual notary notary1 { get; set; }
        [JsonIgnore]
        public virtual person person { get; set; }
        [JsonIgnore]
        public virtual subject subject { get; set; }
        [JsonIgnore]
        public virtual suspention suspention { get; set; }
    }
}
